// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7b0eB9tQmxKWCqAXjXoBP0DspSc_cha0',
    appId: '1:1013939040609:web:ae80b95bf5ce809ed21520',
    messagingSenderId: '1013939040609',
    projectId: 'agenda-mensagem',
    authDomain: 'agenda-mensagem.firebaseapp.com',
    storageBucket: 'agenda-mensagem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXKpj64C0jnN8oGP8JYLV3TCqu2a_SbeA',
    appId: '1:1013939040609:android:80157894f6306cf3d21520',
    messagingSenderId: '1013939040609',
    projectId: 'agenda-mensagem',
    storageBucket: 'agenda-mensagem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX6ztF7iuquLeOu31J-M4j1TYlhBjkMlI',
    appId: '1:1013939040609:ios:f3ae2b06ab80e147d21520',
    messagingSenderId: '1013939040609',
    projectId: 'agenda-mensagem',
    storageBucket: 'agenda-mensagem.appspot.com',
    iosBundleId: 'com.example.agendamentoMensagem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX6ztF7iuquLeOu31J-M4j1TYlhBjkMlI',
    appId: '1:1013939040609:ios:f3ae2b06ab80e147d21520',
    messagingSenderId: '1013939040609',
    projectId: 'agenda-mensagem',
    storageBucket: 'agenda-mensagem.appspot.com',
    iosBundleId: 'com.example.agendamentoMensagem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7b0eB9tQmxKWCqAXjXoBP0DspSc_cha0',
    appId: '1:1013939040609:web:c8195cb61a55e0bed21520',
    messagingSenderId: '1013939040609',
    projectId: 'agenda-mensagem',
    authDomain: 'agenda-mensagem.firebaseapp.com',
    storageBucket: 'agenda-mensagem.appspot.com',
  );
}
